version: '3'

# Creating an ipvlan Docker network so it can monitor the physical network
networks:
  zeeknet:
    driver: ipvlan
    driver_opts:
      parent: ens33
    ipam:
      config:
      - subnet: 198.51.100.0/24
        gateway: 198.51.100.1


#Creating the Zeek container
services:
  zeek:
    build: .
    container_name: zeek
    networks:
      zeeknet:
        ipv4_address: 198.51.100.17


#Making the container interactable
    tty: true

#Mounting volumes stored on the host so we don't need to enter the machine to edit the necessary files
    volumes:
      - ${PWD}/zeek_files:/usr/local/zeek/etc
      - ${PWD}/keys:/root/.ssh

